DB_URL=postgres://postgres:root@localhost:5432/personal_finance?sslmode=disable

migrate-create:
	@migrate create -ext sql -dir migrations -seq $(name)

migrate-up:
	@migrate -path migrations -database "$(DB_URL)" up

migrate-down:
	@migrate -path migrations -database "$(DB_URL)" down 1

migrate-force:
	@migrate -path migrations -database "$(DB_URL)" force $(version)

run:
	@go run cmd/api/main.go